### ISSUE TITLE
Module 2 revision

### ISSUE THREAD

**Issue by silasprincipe** [iobis/otga-course-review#1]
__Improvements/Suggestions__

- Introductory section: Change "as well successfully complete Quiz 2 with a score of ≥80%" for "You also need to successfully..."
- Is it possible to increase the size of the embedded videos (so one does not need to go full screen)?

__Corrections__

-M2-Lesson 1: Determining dataset structure > when to use occurrence core - on the phrase "No information on how the data was sampled or samples were processed is available", better to repeat 'how' for clarity: "No information on how the data was sampled or how samples were processed is available"
-M2-Lesson 2: Understanding and constructing Identifiers > Construct eventID - on the phrase "Repeating the parentEventID: as delimiter) can also make the structure of the dataset easier to understand." correct for "Repeating the parentEventID (using : as delimiter) can also make the structure of the dataset easier to understand."
- In the same section: I would change "Nesting event information in this way also allows you to reduce redundancy and still provide information relevant to each level of sampling." for "Nesting event information in this way allows you to reduce redundancy while still providing information relevant to each level of sampling." [but this is a suggestion]
- M2-Lesson 3: Taxon match > Introduction to Taxonomic Identifiers - it appears to me that some text, at the end, is in a different size/font. (also on "Matching with WoRMS")
- M2-Lesson 3: Taxon match > Non-marine taxa: Change button from "Watch some videos" to something more informative (the same on the title of next page. We could use e.g. "Example videos on how to match species name on WoRMS".
- M2-Lesson 4: Addressing common formatting issues > Dates and times - different font size on first paragraph

General comments: the module is super well done, congrats!

**Comment by EliLawrence** [comment]
Thanks Silas! I made the adjustments as you suggested.
